#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 44
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 35
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_SEMI = 1,
  anon_sym_SQUOTE = 2,
  sym_note = 3,
  anon_sym_PLUS = 4,
  anon_sym_DASH = 5,
  aux_sym_note_length_token1 = 6,
  sym_dots = 7,
  aux_sym_rest_token1 = 8,
  sym_octave_up = 9,
  sym_octave_down = 10,
  anon_sym_o = 11,
  anon_sym_l = 12,
  anon_sym_AT = 13,
  anon_sym_t = 14,
  anon_sym_v = 15,
  aux_sym_key_transpose_token1 = 16,
  sym_source_file = 17,
  sym_channel_groups = 18,
  sym_channel_group = 19,
  sym__item = 20,
  sym_chord = 21,
  sym_note_with_modifier = 22,
  sym_modifier = 23,
  sym_note_length = 24,
  sym_rest = 25,
  sym_octave_set = 26,
  sym_length_set = 27,
  sym_program_change = 28,
  sym_tempo_set = 29,
  sym_velocity_set = 30,
  sym_key_transpose = 31,
  aux_sym_source_file_repeat1 = 32,
  aux_sym_channel_groups_repeat1 = 33,
  aux_sym_chord_repeat1 = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_SQUOTE] = "'",
  [sym_note] = "note",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [aux_sym_note_length_token1] = "note_length_token1",
  [sym_dots] = "dots",
  [aux_sym_rest_token1] = "rest_token1",
  [sym_octave_up] = "octave_up",
  [sym_octave_down] = "octave_down",
  [anon_sym_o] = "o",
  [anon_sym_l] = "l",
  [anon_sym_AT] = "@",
  [anon_sym_t] = "t",
  [anon_sym_v] = "v",
  [aux_sym_key_transpose_token1] = "key_transpose_token1",
  [sym_source_file] = "source_file",
  [sym_channel_groups] = "channel_groups",
  [sym_channel_group] = "channel_group",
  [sym__item] = "_item",
  [sym_chord] = "chord",
  [sym_note_with_modifier] = "note_with_modifier",
  [sym_modifier] = "modifier",
  [sym_note_length] = "note_length",
  [sym_rest] = "rest",
  [sym_octave_set] = "octave_set",
  [sym_length_set] = "length_set",
  [sym_program_change] = "program_change",
  [sym_tempo_set] = "tempo_set",
  [sym_velocity_set] = "velocity_set",
  [sym_key_transpose] = "key_transpose",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_channel_groups_repeat1] = "channel_groups_repeat1",
  [aux_sym_chord_repeat1] = "chord_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym_note] = sym_note,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [aux_sym_note_length_token1] = aux_sym_note_length_token1,
  [sym_dots] = sym_dots,
  [aux_sym_rest_token1] = aux_sym_rest_token1,
  [sym_octave_up] = sym_octave_up,
  [sym_octave_down] = sym_octave_down,
  [anon_sym_o] = anon_sym_o,
  [anon_sym_l] = anon_sym_l,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_t] = anon_sym_t,
  [anon_sym_v] = anon_sym_v,
  [aux_sym_key_transpose_token1] = aux_sym_key_transpose_token1,
  [sym_source_file] = sym_source_file,
  [sym_channel_groups] = sym_channel_groups,
  [sym_channel_group] = sym_channel_group,
  [sym__item] = sym__item,
  [sym_chord] = sym_chord,
  [sym_note_with_modifier] = sym_note_with_modifier,
  [sym_modifier] = sym_modifier,
  [sym_note_length] = sym_note_length,
  [sym_rest] = sym_rest,
  [sym_octave_set] = sym_octave_set,
  [sym_length_set] = sym_length_set,
  [sym_program_change] = sym_program_change,
  [sym_tempo_set] = sym_tempo_set,
  [sym_velocity_set] = sym_velocity_set,
  [sym_key_transpose] = sym_key_transpose,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_channel_groups_repeat1] = aux_sym_channel_groups_repeat1,
  [aux_sym_chord_repeat1] = aux_sym_chord_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_note] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_note_length_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_dots] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_rest_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_octave_up] = {
    .visible = true,
    .named = true,
  },
  [sym_octave_down] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_o] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_l] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_t] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_v] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_key_transpose_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_channel_groups] = {
    .visible = true,
    .named = true,
  },
  [sym_channel_group] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_chord] = {
    .visible = true,
    .named = true,
  },
  [sym_note_with_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_note_length] = {
    .visible = true,
    .named = true,
  },
  [sym_rest] = {
    .visible = true,
    .named = true,
  },
  [sym_octave_set] = {
    .visible = true,
    .named = true,
  },
  [sym_length_set] = {
    .visible = true,
    .named = true,
  },
  [sym_program_change] = {
    .visible = true,
    .named = true,
  },
  [sym_tempo_set] = {
    .visible = true,
    .named = true,
  },
  [sym_velocity_set] = {
    .visible = true,
    .named = true,
  },
  [sym_key_transpose] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_channel_groups_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_chord_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == '+') ADVANCE(7);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == ';') ADVANCE(4);
      if (lookahead == '<') ADVANCE(12);
      if (lookahead == '>') ADVANCE(13);
      if (lookahead == '@') ADVANCE(16);
      if (lookahead == 'K') ADVANCE(1);
      if (lookahead == 'k') ADVANCE(2);
      if (lookahead == 'l') ADVANCE(15);
      if (lookahead == 'o') ADVANCE(14);
      if (lookahead == 't') ADVANCE(17);
      if (lookahead == 'v') ADVANCE(18);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      if (('A' <= lookahead && lookahead <= 'G') ||
          ('a' <= lookahead && lookahead <= 'g')) ADVANCE(6);
      END_STATE();
    case 1:
      if (lookahead == 'T') ADVANCE(19);
      END_STATE();
    case 2:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_note);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_note_length_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_dots);
      if (lookahead == '.') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_rest_token1);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_octave_up);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_octave_down);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_o);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_l);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_t);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_v);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_key_transpose_token1);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_note] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [aux_sym_note_length_token1] = ACTIONS(1),
    [sym_dots] = ACTIONS(1),
    [aux_sym_rest_token1] = ACTIONS(1),
    [sym_octave_up] = ACTIONS(1),
    [sym_octave_down] = ACTIONS(1),
    [anon_sym_o] = ACTIONS(1),
    [anon_sym_l] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_t] = ACTIONS(1),
    [anon_sym_v] = ACTIONS(1),
    [aux_sym_key_transpose_token1] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(41),
    [sym_channel_groups] = STATE(43),
    [sym_channel_group] = STATE(34),
    [sym__item] = STATE(4),
    [sym_chord] = STATE(4),
    [sym_note_with_modifier] = STATE(4),
    [sym_rest] = STATE(4),
    [sym_octave_set] = STATE(4),
    [sym_length_set] = STATE(4),
    [sym_program_change] = STATE(4),
    [sym_tempo_set] = STATE(4),
    [sym_velocity_set] = STATE(4),
    [sym_key_transpose] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_SQUOTE] = ACTIONS(5),
    [sym_note] = ACTIONS(7),
    [aux_sym_rest_token1] = ACTIONS(9),
    [sym_octave_up] = ACTIONS(11),
    [sym_octave_down] = ACTIONS(11),
    [anon_sym_o] = ACTIONS(13),
    [anon_sym_l] = ACTIONS(15),
    [anon_sym_AT] = ACTIONS(17),
    [anon_sym_t] = ACTIONS(19),
    [anon_sym_v] = ACTIONS(21),
    [aux_sym_key_transpose_token1] = ACTIONS(23),
  },
  [2] = {
    [sym__item] = STATE(3),
    [sym_chord] = STATE(3),
    [sym_note_with_modifier] = STATE(3),
    [sym_rest] = STATE(3),
    [sym_octave_set] = STATE(3),
    [sym_length_set] = STATE(3),
    [sym_program_change] = STATE(3),
    [sym_tempo_set] = STATE(3),
    [sym_velocity_set] = STATE(3),
    [sym_key_transpose] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_SEMI] = ACTIONS(25),
    [anon_sym_SQUOTE] = ACTIONS(5),
    [sym_note] = ACTIONS(7),
    [aux_sym_rest_token1] = ACTIONS(9),
    [sym_octave_up] = ACTIONS(27),
    [sym_octave_down] = ACTIONS(27),
    [anon_sym_o] = ACTIONS(13),
    [anon_sym_l] = ACTIONS(15),
    [anon_sym_AT] = ACTIONS(17),
    [anon_sym_t] = ACTIONS(19),
    [anon_sym_v] = ACTIONS(21),
    [aux_sym_key_transpose_token1] = ACTIONS(23),
  },
  [3] = {
    [sym__item] = STATE(3),
    [sym_chord] = STATE(3),
    [sym_note_with_modifier] = STATE(3),
    [sym_rest] = STATE(3),
    [sym_octave_set] = STATE(3),
    [sym_length_set] = STATE(3),
    [sym_program_change] = STATE(3),
    [sym_tempo_set] = STATE(3),
    [sym_velocity_set] = STATE(3),
    [sym_key_transpose] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(29),
    [anon_sym_SEMI] = ACTIONS(29),
    [anon_sym_SQUOTE] = ACTIONS(31),
    [sym_note] = ACTIONS(34),
    [aux_sym_rest_token1] = ACTIONS(37),
    [sym_octave_up] = ACTIONS(40),
    [sym_octave_down] = ACTIONS(40),
    [anon_sym_o] = ACTIONS(43),
    [anon_sym_l] = ACTIONS(46),
    [anon_sym_AT] = ACTIONS(49),
    [anon_sym_t] = ACTIONS(52),
    [anon_sym_v] = ACTIONS(55),
    [aux_sym_key_transpose_token1] = ACTIONS(58),
  },
  [4] = {
    [sym__item] = STATE(3),
    [sym_chord] = STATE(3),
    [sym_note_with_modifier] = STATE(3),
    [sym_rest] = STATE(3),
    [sym_octave_set] = STATE(3),
    [sym_length_set] = STATE(3),
    [sym_program_change] = STATE(3),
    [sym_tempo_set] = STATE(3),
    [sym_velocity_set] = STATE(3),
    [sym_key_transpose] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(61),
    [anon_sym_SEMI] = ACTIONS(25),
    [anon_sym_SQUOTE] = ACTIONS(5),
    [sym_note] = ACTIONS(7),
    [aux_sym_rest_token1] = ACTIONS(9),
    [sym_octave_up] = ACTIONS(27),
    [sym_octave_down] = ACTIONS(27),
    [anon_sym_o] = ACTIONS(13),
    [anon_sym_l] = ACTIONS(15),
    [anon_sym_AT] = ACTIONS(17),
    [anon_sym_t] = ACTIONS(19),
    [anon_sym_v] = ACTIONS(21),
    [aux_sym_key_transpose_token1] = ACTIONS(23),
  },
  [5] = {
    [sym_channel_group] = STATE(35),
    [sym__item] = STATE(2),
    [sym_chord] = STATE(2),
    [sym_note_with_modifier] = STATE(2),
    [sym_rest] = STATE(2),
    [sym_octave_set] = STATE(2),
    [sym_length_set] = STATE(2),
    [sym_program_change] = STATE(2),
    [sym_tempo_set] = STATE(2),
    [sym_velocity_set] = STATE(2),
    [sym_key_transpose] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_SQUOTE] = ACTIONS(5),
    [sym_note] = ACTIONS(7),
    [aux_sym_rest_token1] = ACTIONS(9),
    [sym_octave_up] = ACTIONS(63),
    [sym_octave_down] = ACTIONS(63),
    [anon_sym_o] = ACTIONS(13),
    [anon_sym_l] = ACTIONS(15),
    [anon_sym_AT] = ACTIONS(17),
    [anon_sym_t] = ACTIONS(19),
    [anon_sym_v] = ACTIONS(21),
    [aux_sym_key_transpose_token1] = ACTIONS(23),
  },
  [6] = {
    [sym_modifier] = STATE(7),
    [sym_note_length] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(65),
    [anon_sym_SEMI] = ACTIONS(65),
    [anon_sym_SQUOTE] = ACTIONS(65),
    [sym_note] = ACTIONS(65),
    [anon_sym_PLUS] = ACTIONS(67),
    [anon_sym_DASH] = ACTIONS(67),
    [aux_sym_note_length_token1] = ACTIONS(69),
    [sym_dots] = ACTIONS(71),
    [aux_sym_rest_token1] = ACTIONS(65),
    [sym_octave_up] = ACTIONS(65),
    [sym_octave_down] = ACTIONS(65),
    [anon_sym_o] = ACTIONS(65),
    [anon_sym_l] = ACTIONS(65),
    [anon_sym_AT] = ACTIONS(65),
    [anon_sym_t] = ACTIONS(65),
    [anon_sym_v] = ACTIONS(65),
    [aux_sym_key_transpose_token1] = ACTIONS(65),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(69), 1,
      aux_sym_note_length_token1,
    ACTIONS(75), 1,
      sym_dots,
    STATE(10), 1,
      sym_note_length,
    ACTIONS(73), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SQUOTE,
      sym_note,
      aux_sym_rest_token1,
      sym_octave_up,
      sym_octave_down,
      anon_sym_o,
      anon_sym_l,
      anon_sym_AT,
      anon_sym_t,
      anon_sym_v,
      aux_sym_key_transpose_token1,
  [25] = 4,
    ACTIONS(69), 1,
      aux_sym_note_length_token1,
    ACTIONS(79), 1,
      sym_dots,
    STATE(12), 1,
      sym_note_length,
    ACTIONS(77), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SQUOTE,
      sym_note,
      aux_sym_rest_token1,
      sym_octave_up,
      sym_octave_down,
      anon_sym_o,
      anon_sym_l,
      anon_sym_AT,
      anon_sym_t,
      anon_sym_v,
      aux_sym_key_transpose_token1,
  [50] = 1,
    ACTIONS(81), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SQUOTE,
      sym_note,
      aux_sym_note_length_token1,
      sym_dots,
      aux_sym_rest_token1,
      sym_octave_up,
      sym_octave_down,
      anon_sym_o,
      anon_sym_l,
      anon_sym_AT,
      anon_sym_t,
      anon_sym_v,
      aux_sym_key_transpose_token1,
  [68] = 2,
    ACTIONS(85), 1,
      sym_dots,
    ACTIONS(83), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SQUOTE,
      sym_note,
      aux_sym_rest_token1,
      sym_octave_up,
      sym_octave_down,
      anon_sym_o,
      anon_sym_l,
      anon_sym_AT,
      anon_sym_t,
      anon_sym_v,
      aux_sym_key_transpose_token1,
  [87] = 2,
    ACTIONS(89), 1,
      sym_dots,
    ACTIONS(87), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SQUOTE,
      sym_note,
      aux_sym_rest_token1,
      sym_octave_up,
      sym_octave_down,
      anon_sym_o,
      anon_sym_l,
      anon_sym_AT,
      anon_sym_t,
      anon_sym_v,
      aux_sym_key_transpose_token1,
  [106] = 2,
    ACTIONS(93), 1,
      sym_dots,
    ACTIONS(91), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SQUOTE,
      sym_note,
      aux_sym_rest_token1,
      sym_octave_up,
      sym_octave_down,
      anon_sym_o,
      anon_sym_l,
      anon_sym_AT,
      anon_sym_t,
      anon_sym_v,
      aux_sym_key_transpose_token1,
  [125] = 1,
    ACTIONS(95), 14,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SQUOTE,
      sym_note,
      sym_dots,
      aux_sym_rest_token1,
      sym_octave_up,
      sym_octave_down,
      anon_sym_o,
      anon_sym_l,
      anon_sym_AT,
      anon_sym_t,
      anon_sym_v,
      aux_sym_key_transpose_token1,
  [142] = 2,
    ACTIONS(75), 1,
      sym_dots,
    ACTIONS(73), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SQUOTE,
      sym_note,
      aux_sym_rest_token1,
      sym_octave_up,
      sym_octave_down,
      anon_sym_o,
      anon_sym_l,
      anon_sym_AT,
      anon_sym_t,
      anon_sym_v,
      aux_sym_key_transpose_token1,
  [161] = 1,
    ACTIONS(97), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SQUOTE,
      sym_note,
      aux_sym_rest_token1,
      sym_octave_up,
      sym_octave_down,
      anon_sym_o,
      anon_sym_l,
      anon_sym_AT,
      anon_sym_t,
      anon_sym_v,
      aux_sym_key_transpose_token1,
  [177] = 1,
    ACTIONS(99), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SQUOTE,
      sym_note,
      aux_sym_rest_token1,
      sym_octave_up,
      sym_octave_down,
      anon_sym_o,
      anon_sym_l,
      anon_sym_AT,
      anon_sym_t,
      anon_sym_v,
      aux_sym_key_transpose_token1,
  [193] = 1,
    ACTIONS(101), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SQUOTE,
      sym_note,
      aux_sym_rest_token1,
      sym_octave_up,
      sym_octave_down,
      anon_sym_o,
      anon_sym_l,
      anon_sym_AT,
      anon_sym_t,
      anon_sym_v,
      aux_sym_key_transpose_token1,
  [209] = 1,
    ACTIONS(103), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SQUOTE,
      sym_note,
      aux_sym_rest_token1,
      sym_octave_up,
      sym_octave_down,
      anon_sym_o,
      anon_sym_l,
      anon_sym_AT,
      anon_sym_t,
      anon_sym_v,
      aux_sym_key_transpose_token1,
  [225] = 1,
    ACTIONS(105), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SQUOTE,
      sym_note,
      aux_sym_rest_token1,
      sym_octave_up,
      sym_octave_down,
      anon_sym_o,
      anon_sym_l,
      anon_sym_AT,
      anon_sym_t,
      anon_sym_v,
      aux_sym_key_transpose_token1,
  [241] = 1,
    ACTIONS(73), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SQUOTE,
      sym_note,
      aux_sym_rest_token1,
      sym_octave_up,
      sym_octave_down,
      anon_sym_o,
      anon_sym_l,
      anon_sym_AT,
      anon_sym_t,
      anon_sym_v,
      aux_sym_key_transpose_token1,
  [257] = 1,
    ACTIONS(91), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SQUOTE,
      sym_note,
      aux_sym_rest_token1,
      sym_octave_up,
      sym_octave_down,
      anon_sym_o,
      anon_sym_l,
      anon_sym_AT,
      anon_sym_t,
      anon_sym_v,
      aux_sym_key_transpose_token1,
  [273] = 1,
    ACTIONS(83), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SQUOTE,
      sym_note,
      aux_sym_rest_token1,
      sym_octave_up,
      sym_octave_down,
      anon_sym_o,
      anon_sym_l,
      anon_sym_AT,
      anon_sym_t,
      anon_sym_v,
      aux_sym_key_transpose_token1,
  [289] = 1,
    ACTIONS(107), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SQUOTE,
      sym_note,
      aux_sym_rest_token1,
      sym_octave_up,
      sym_octave_down,
      anon_sym_o,
      anon_sym_l,
      anon_sym_AT,
      anon_sym_t,
      anon_sym_v,
      aux_sym_key_transpose_token1,
  [305] = 1,
    ACTIONS(109), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SQUOTE,
      sym_note,
      aux_sym_rest_token1,
      sym_octave_up,
      sym_octave_down,
      anon_sym_o,
      anon_sym_l,
      anon_sym_AT,
      anon_sym_t,
      anon_sym_v,
      aux_sym_key_transpose_token1,
  [321] = 1,
    ACTIONS(111), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SQUOTE,
      sym_note,
      aux_sym_rest_token1,
      sym_octave_up,
      sym_octave_down,
      anon_sym_o,
      anon_sym_l,
      anon_sym_AT,
      anon_sym_t,
      anon_sym_v,
      aux_sym_key_transpose_token1,
  [337] = 1,
    ACTIONS(113), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SQUOTE,
      sym_note,
      aux_sym_rest_token1,
      sym_octave_up,
      sym_octave_down,
      anon_sym_o,
      anon_sym_l,
      anon_sym_AT,
      anon_sym_t,
      anon_sym_v,
      aux_sym_key_transpose_token1,
  [353] = 1,
    ACTIONS(115), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SQUOTE,
      sym_note,
      aux_sym_rest_token1,
      sym_octave_up,
      sym_octave_down,
      anon_sym_o,
      anon_sym_l,
      anon_sym_AT,
      anon_sym_t,
      anon_sym_v,
      aux_sym_key_transpose_token1,
  [369] = 3,
    ACTIONS(117), 1,
      anon_sym_SQUOTE,
    ACTIONS(119), 1,
      sym_note,
    STATE(28), 2,
      sym_note_with_modifier,
      aux_sym_chord_repeat1,
  [380] = 3,
    ACTIONS(7), 1,
      sym_note,
    ACTIONS(122), 1,
      anon_sym_SQUOTE,
    STATE(28), 2,
      sym_note_with_modifier,
      aux_sym_chord_repeat1,
  [391] = 3,
    ACTIONS(124), 1,
      ts_builtin_sym_end,
    ACTIONS(126), 1,
      anon_sym_SEMI,
    STATE(32), 1,
      aux_sym_channel_groups_repeat1,
  [401] = 2,
    ACTIONS(7), 1,
      sym_note,
    STATE(29), 2,
      sym_note_with_modifier,
      aux_sym_chord_repeat1,
  [409] = 3,
    ACTIONS(128), 1,
      ts_builtin_sym_end,
    ACTIONS(130), 1,
      anon_sym_SEMI,
    STATE(32), 1,
      aux_sym_channel_groups_repeat1,
  [419] = 2,
    ACTIONS(133), 1,
      anon_sym_DASH,
    ACTIONS(135), 1,
      aux_sym_note_length_token1,
  [426] = 2,
    ACTIONS(126), 1,
      anon_sym_SEMI,
    STATE(30), 1,
      aux_sym_channel_groups_repeat1,
  [433] = 1,
    ACTIONS(128), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [438] = 1,
    ACTIONS(137), 1,
      aux_sym_note_length_token1,
  [442] = 1,
    ACTIONS(139), 1,
      aux_sym_note_length_token1,
  [446] = 1,
    ACTIONS(141), 1,
      aux_sym_note_length_token1,
  [450] = 1,
    ACTIONS(143), 1,
      aux_sym_note_length_token1,
  [454] = 1,
    ACTIONS(145), 1,
      aux_sym_note_length_token1,
  [458] = 1,
    ACTIONS(147), 1,
      ts_builtin_sym_end,
  [462] = 1,
    ACTIONS(149), 1,
      aux_sym_note_length_token1,
  [466] = 1,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 25,
  [SMALL_STATE(9)] = 50,
  [SMALL_STATE(10)] = 68,
  [SMALL_STATE(11)] = 87,
  [SMALL_STATE(12)] = 106,
  [SMALL_STATE(13)] = 125,
  [SMALL_STATE(14)] = 142,
  [SMALL_STATE(15)] = 161,
  [SMALL_STATE(16)] = 177,
  [SMALL_STATE(17)] = 193,
  [SMALL_STATE(18)] = 209,
  [SMALL_STATE(19)] = 225,
  [SMALL_STATE(20)] = 241,
  [SMALL_STATE(21)] = 257,
  [SMALL_STATE(22)] = 273,
  [SMALL_STATE(23)] = 289,
  [SMALL_STATE(24)] = 305,
  [SMALL_STATE(25)] = 321,
  [SMALL_STATE(26)] = 337,
  [SMALL_STATE(27)] = 353,
  [SMALL_STATE(28)] = 369,
  [SMALL_STATE(29)] = 380,
  [SMALL_STATE(30)] = 391,
  [SMALL_STATE(31)] = 401,
  [SMALL_STATE(32)] = 409,
  [SMALL_STATE(33)] = 419,
  [SMALL_STATE(34)] = 426,
  [SMALL_STATE(35)] = 433,
  [SMALL_STATE(36)] = 438,
  [SMALL_STATE(37)] = 442,
  [SMALL_STATE(38)] = 446,
  [SMALL_STATE(39)] = 450,
  [SMALL_STATE(40)] = 454,
  [SMALL_STATE(41)] = 458,
  [SMALL_STATE(42)] = 462,
  [SMALL_STATE(43)] = 466,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_channel_group, 1),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(31),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(6),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(8),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(3),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(42),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(40),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(39),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(38),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(37),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(33),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_with_modifier, 1),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_with_modifier, 2),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rest, 1),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_modifier, 1),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_with_modifier, 3),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_length_set, 2),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rest, 2),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_length, 1),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chord, 3),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rest, 3),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_with_modifier, 4),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_transpose, 3),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_length_set, 3),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_octave_set, 2),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_transpose, 2),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program_change, 2),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tempo_set, 2),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_velocity_set, 2),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_chord_repeat1, 2),
  [119] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chord_repeat1, 2), SHIFT_REPEAT(6),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_channel_groups, 2),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_channel_groups_repeat1, 2),
  [130] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_channel_groups_repeat1, 2), SHIFT_REPEAT(5),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [147] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_mml(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
